"""
Alembic migration environment for beetkeeper's SQLite database.

`target_metadata` is `SQLModel.metadata`, populated by importing `beetkeeper.db.models` (which registers
every table). The connection URL is resolved in priority order:
    1. an alembic ``-x db_url=...`` argument,
    2. the explicit beetkeeper main-options set by `beetkeeper.db.migrations`,
    3. the ``BEETKEEPER_CONFIG`` env var (loaded via `beetkeeper.settings.load_config`),
    4. the ``sqlalchemy.url`` ini option.

Supports offline (`--sql`) generation and async-online application. See:
    https://alembic.sqlalchemy.org/en/latest/offline.html
"""

import asyncio
import os
from logging.config import fileConfig
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlmodel import SQLModel

# Importing the models module registers all ORM tables onto `SQLModel.metadata`.
import beetkeeper.db.models  # noqa: F401
from beetkeeper.db.migrations import ASYNC_URL_OPT, SYNC_URL_OPT
from beetkeeper.settings import CONFIG_PATH_ENVVAR, load_config

if TYPE_CHECKING:
    from alembic.autogenerate.api import AutogenContext

config = context.config

# Only configure logging from a real ini file (None when the Config is built programmatically).
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def _resolve_url(*, prefer_async: bool) -> str:
    """Resolves the SQLAlchemy URL for the current run (see module docstring for precedence)."""
    x_args = context.get_x_argument(as_dictionary=True)
    if "db_url" in x_args:
        return x_args["db_url"]

    opt_url = config.get_main_option(ASYNC_URL_OPT if prefer_async else SYNC_URL_OPT)
    if opt_url:
        return opt_url

    conf_path = os.environ.get(CONFIG_PATH_ENVVAR)
    if conf_path:
        database = load_config(Path(conf_path)).database
        return database.async_url if prefer_async else database.sync_url

    ini_url = config.get_main_option("sqlalchemy.url")
    if ini_url:
        return ini_url

    raise RuntimeError(
        "No database URL for alembic. Provide `-x db_url=...`, set "
        f"`{CONFIG_PATH_ENVVAR}`, or set `sqlalchemy.url` in the ini file."
    )


def run_migrations_offline() -> None:
    """Emit migrations as SQL against a URL only (no DB-API connection); used by `--sql` mode."""
    context.configure(
        url=_resolve_url(prefer_async=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,  # SQLite cannot ALTER in place; batch mode rebuilds tables.
    )
    with context.begin_transaction():
        context.run_migrations()


def _render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Render SQLModel's `AutoString` as a plain `sa.String` so autogenerated scripts need no sqlmodel import."""
    from sqlmodel.sql.sqltypes import AutoString

    if type_ == "type" and isinstance(obj, AutoString):
        length = getattr(obj, "length", None)
        return f"sa.String(length={length})" if length else "sa.String()"
    return False


def _do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection, target_metadata=target_metadata, render_as_batch=True, render_item=_render_item
    )
    with context.begin_transaction():
        context.run_migrations()


async def _run_async_migrations() -> None:
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = _resolve_url(prefer_async=True)
    connectable = async_engine_from_config(configuration, prefix="sqlalchemy.", poolclass=pool.NullPool)
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Apply migrations through a live async (aiosqlite) connection."""
    asyncio.run(_run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
