resource(name="pytyped-marker", source="py.typed")
python_sources(
    description="The root module of beetkeeper source.",
    dependencies=["./api:api", "./core:core", "./db:db", ":pytyped-marker", "./settings:settings"],
)
