python_test_utils(
    name="events-plugin-integration-test-utils",
    dependencies=["//src/beetsplug/beetkeeper_plugin:beetkeeper_plugin", "//src/python/beetkeeper:beetkeeper"],
)
python_tests(dependencies=[":events-plugin-integration-test-utils"])
