shell_sources()
run_shell_command(
    name="run-test-server",
    command="./build_scripts/run-test-server.sh",
    workdir="/",
    execution_dependencies=["build_scripts/run-test-server.sh", "//:beetkeeper-server-image"],
)
