#!/usr/bin/env bash
#
# Regenerates the pex "complete platform" JSONs under 3rdparty/platforms/.
# See docs/contributor_docs/building_artifacts.md#regenerating-the-complete-platform-jsons
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_dir="${repo_root}/3rdparty/platforms"
all_slugs=(linux-amd64 linux-arm64 macos-amd64 macos-arm64)
inspect_args=(interpreter inspect --markers --tags --indent=2)
docker_image="" python_version="" pex_version="" scratch=""

usage() {
	cat <<EOF
usage: $(basename "$0") [-h|--help] [SLUG ...]

Regenerates 3rdparty/platforms/<SLUG>.json for each SLUG (default: ${all_slugs[*]}).
linux-* slugs need docker. macos-* slugs need a macOS host with uv; macos-amd64 on Apple silicon needs Rosetta 2.

Environment overrides (defaults are derived from the repo):
  PEX_VERSION     pex release that runs the inspection (default: Pants' pinned [pex-cli] version)
  DOCKER_IMAGE    image the linux-* interpreters come from (default: the Dockerfile 'app' stage base image)
  PYTHON_VERSION  MAJOR.MINOR of uv's python-build-standalone for macos-* (default: DOCKER_IMAGE's tag)
EOF
}

die() {
	echo "error: $*" >&2
	exit 1
}

need() {
	command -v "$1" >/dev/null 2>&1 || die "'$1' not found on PATH"
}

pex_version_from_pants() {
	need pants
	(cd "${repo_root}" && pants help-all) |
		jq -er '.scope_to_help_info["pex-cli"].advanced[] | select(.config_key == "version") | .default' |
		sed 's/^v//'
}

app_image_from_dockerfile() {
	awk 'toupper($1) == "FROM" && toupper($(NF - 1)) == "AS" && $NF == "app" { print $2 }' "${repo_root}/Dockerfile"
}

uv_arch() {
	case "$1" in
	macos-arm64) echo aarch64 ;;
	macos-amd64) echo x86_64 ;;
	esac
}

check_macos_host() {
	[[ "$(uname -s)" == Darwin ]] || die "$1 must be generated on a macOS host"
	need uv
	case "$1:$(uname -m)" in
	macos-arm64:arm64 | macos-amd64:x86_64) ;;
	macos-amd64:arm64)
		arch -x86_64 /usr/bin/true 2>/dev/null ||
			die "$1 on Apple silicon needs Rosetta 2: softwareupdate --install-rosetta"
		;;
	macos-arm64:x86_64) die "$1 can only be generated on an Apple-silicon Mac" ;;
	esac
}

inspect_linux() {
	docker run --rm --pull=always --platform "linux/$1" \
		-e PIP_DISABLE_PIP_VERSION_CHECK=1 -e PIP_ROOT_USER_ACTION=ignore \
		"${docker_image}" sh -c "pip install -q pex==${pex_version} && pex3 ${inspect_args[*]}"
}

inspect_macos() {
	(
		cd "${scratch}" && unset VIRTUAL_ENV &&
			uv run --no-project --managed-python \
				--python "cpython-${python_version}-macos-$1-none" \
				--with "pex==${pex_version}" -- pex3 "${inspect_args[@]}"
	)
}

postprocess() {
	jq --arg slug "$1" --arg source "$2" --arg pex "${pex_version}" '{
		__meta_data__: "Complete platform for cp\(.marker_environment.python_version | sub("\\."; "")) \($slug): CPython \(.marker_environment.python_full_version) from \($source); generated by build_scripts/generate-complete-platforms.sh with pex \($pex). Do not hand-edit.",
		marker_environment,
		compatible_tags
	}'
}

validate() {
	local sys_platform machine
	case "$1" in
	linux-amd64) sys_platform=linux machine=x86_64 ;;
	linux-arm64) sys_platform=linux machine=aarch64 ;;
	macos-amd64) sys_platform=darwin machine=x86_64 ;;
	macos-arm64) sys_platform=darwin machine=arm64 ;;
	esac
	jq -e --arg sp "${sys_platform}" --arg m "${machine}" --arg py "${python_version}" '
		.marker_environment.sys_platform == $sp
		and .marker_environment.platform_machine == $m
		and .marker_environment.python_version == $py
		and (.compatible_tags | length) > 0
		and (.compatible_tags | index("py3-none-any")) != null
		and (.compatible_tags[0] | startswith("cp\($py | sub("\\."; ""))-cp"))
	' "$2" >/dev/null ||
		die "$1: generated JSON failed validation: $(jq -c '{sys_platform: .marker_environment.sys_platform, platform_machine: .marker_environment.platform_machine, python_version: .marker_environment.python_version, n_tags: (.compatible_tags | length), first_tag: .compatible_tags[0]}' "$2")"
}

generate() {
	local slug="$1" arch raw source tmp
	case "${slug}" in
	linux-*)
		need docker
		arch="${slug#linux-}"
		source="${docker_image} (linux/${arch})"
		raw="$(inspect_linux "${arch}")"
		;;
	macos-*)
		check_macos_host "${slug}"
		arch="$(uv_arch "${slug}")"
		source="uv cpython-${python_version}-macos-${arch}-none on macOS $(sw_vers -productVersion)"
		raw="$(inspect_macos "${arch}")"
		;;
	esac
	tmp="${scratch}/${slug}.json"
	postprocess "${slug}" "${source}" <<<"${raw}" >"${tmp}"
	validate "${slug}" "${tmp}"
	mv "${tmp}" "${out_dir}/${slug}.json"
	echo "wrote 3rdparty/platforms/${slug}.json ($(jq -r '"\(.compatible_tags | length) tags, CPython \(.marker_environment.python_full_version)"' "${out_dir}/${slug}.json"))"
}

main() {
	local slugs=() slug
	if (($# == 0)); then
		slugs=("${all_slugs[@]}")
	else
		slugs=("$@")
	fi
	for slug in "${slugs[@]}"; do
		case "${slug}" in
		-h | --help)
			usage
			exit 0
			;;
		esac
		[[ " ${all_slugs[*]} " == *" ${slug} "* ]] || die "unknown slug '${slug}' (expected one of: ${all_slugs[*]})"
	done
	need jq
	docker_image="${DOCKER_IMAGE:-$(app_image_from_dockerfile)}"
	[[ -n "${docker_image}" ]] || die "could not parse the 'app' stage base image from Dockerfile"
	python_version="${PYTHON_VERSION:-$(sed -E 's/^[^:]+:([0-9]+\.[0-9]+).*$/\1/' <<<"${docker_image}")}"
	pex_version="${PEX_VERSION:-$(pex_version_from_pants)}"
	[[ -n "${pex_version}" ]] || die "could not determine the pex version (set PEX_VERSION)"
	scratch="$(mktemp -d)"
	trap 'rm -rf "${scratch}"' EXIT
	echo "pex ${pex_version}; docker image ${docker_image}; python ${python_version}" >&2
	for slug in "${slugs[@]}"; do
		generate "${slug}"
	done
}

main "$@"
