python_test_utils(name="plugin-test-utils", dependencies=["src/beetsplug/beetkeeper_plugin:beetkeeper_plugin"])
python_tests(dependencies=[":plugin-test-utils", "src/beetsplug/beetkeeper_plugin:beetkeeper_plugin"])
