target(
    name="static-app-files",
    description="Meta-target holding all the static resource files for the `HTMLResponse` route functions.",
    dependencies=["./css:classless-file", "./html_templates:all-html-templates", "./js:htmx-file", "./img:img"],
)
