python_test_utils(
    name="events-plugin-integration-test-utils",
    dependencies=[
        "//plugin/src/beetsplug/beetkeeper_plugin:beetkeeper_plugin",
        "//beetkeeper-core/src/beetkeeper:beetkeeper",
    ],
)
python_tests(dependencies=[":events-plugin-integration-test-utils"])
