python_test_utils(name="plugin-test-utils", dependencies=["plugin/src/beetsplug/beetkeeper_plugin:beetkeeper_plugin"])
python_tests(dependencies=[":plugin-test-utils", "plugin/src/beetsplug/beetkeeper_plugin:beetkeeper_plugin"])
