---
log_level: INFO
beets_config_filepath: ~/appdata/beets/config.yaml
server:
  hostname: localhost
  port: 6969
  server_workers: 4
database:
  # beetkeeper's own SQLite db (separate from the beets library). Created on first migration.
  sqlite_path: ~/appdata/beetkeeper/beetkeeper.db
