python_sources(
    dependencies=[
        "./static:static-app-files",
        "//src/python:app-requirements#beets",
        "!//src/beetsplug:plugin-requirements",
        "!//3rdparty/python:test-requirements#httpx",
    ]
)
