resource(name="pytyped-marker", source="py.typed")
python_sources(
    description="The namespaced package for `beetsplug.beetkeeper_plugin` source.",
    dependencies=[":pytyped-marker", "//src/beetsplug:plugin-requirements", "!//src/python:app-requirements"],
)
