python_sources(
    dependencies=[
        "./static:static-app-files",
        "//beetkeeper-core:app-requirements#beets",
        "!//plugin:plugin-requirements",
        "!//3rdparty/python:test-requirements#httpx",
    ]
)
